// import './css/reboot.css';
// import './css/index.css';
// import './sass/test.scss';
require("./css/reboot.css");
require("./css/index.css");
require("./sass/test.scss");
import App from "./app";
const arr = [1, 2, 3];
const iAmJavascriptES6 = () => console.log(...arr);
window.iAmJavascriptES6 = iAmJavascriptES6;